name: Build - Ubuntu

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container: wpilib/roborio-cross-ubuntu:2022-18.04

    steps:
      - uses: actions/checkout@v3

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build
      - name: Compile and run tests on robot code
        run: ./gradlew build